### ISSUE TITLE
Commit 878043b causes error "Cannot read property 'MemAvailable'" in FreeNAS 10.3

### ISSUE THREAD

**Issue by jsegaert** [hexparrot/mineos-node#244]
The latest commits do no longer build on FreeNAS 10.3 (based on FreeBSD 10.3).  The following error shows in /var/log/mineos.log:
```  "stack": [
    "TypeError: Cannot read property 'MemAvailable' of undefined",
    "  at /usr/local/games/minecraft/server.js:96:29",
    "  at /usr/local/games/minecraft/node_modules/async/lib/async.js:52:16",
    "  at /usr/local/games/minecraft/node_modules/async/lib/async.js:1209:30",
    "  at ReadFileContext.callback (/usr/local/games/minecraft/node_modules/procfs-stats/index.js:215:20)",
    "  at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:359:13)"
  ]
```
When I roll back file server.js to the version before commit 878043b, the system builds fine:
```git show "878043b~1":server.js > server.js```

**Comment by hexparrot** [comment]
I committed 85486095435cb49a23607eaa90c0392ba49a034a today to address this.  It should now fallback to os.memfree (which was the default previously).  Can you confirm this solves your issue?

**Comment by jsegaert** [comment]
No dice...

I think you want **os.freemem()** instead of instead of **os.memfree()**

```
{
  "level": "info",
  "message": "Starting up server, using commit: 8548609 fallback to os.memfree if procfs-stats module fails\n",
  "timestamp": "2017-06-13T01:27:53.052Z"
}
"stack": [
    "TypeError: os.memfree is not a function",
    "    at /usr/local/games/minecraft/server.js:96:69",
    "    at /usr/local/games/minecraft/node_modules/async/lib/async.js:52:16",
    "    at /usr/local/games/minecraft/node_modules/async/lib/async.js:1209:30",
    "    at ReadFileContext.callback (/usr/local/games/minecraft/node_modules/procfs-stats/index.js:215:20)",
    "    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:359:13)"
  ]```

**Comment by hexparrot** [comment]
What I _meant_ to say was just that!  e326dfaff22132c0420206839d667c3222b0afbb

(sorry)

**Comment by jsegaert** [comment]
OK, I retested and can confirm that it is now working! :-)
This issue can be closed.  Thank you!
